services:
  db:
    image: mysql:8.0
    container_name: symfony_db
    ports:
      - "3306:3306"
    env_file: ".env.local"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    env_file: ".env.local"