name: luxwatch
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file: ".env.local"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    env_file: ".env.local"